config/routes.rb
Rails.application.routes.draw do

  resources :companies do
    resources :locations
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :locations, dependent: :destroy
	validates :company, presence: true,
						:uniqueness => true
  default_scope {order('company ASC')}
	
  scope :search_query, -> (company) { where("company like ?", "#{company}%")}



end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def new
    	@company = Company.new
    end
    def edit
    	@company = Company.find(params[:id])
    end
    def index
        @companies = Company.all
    end

    def show
    	@company = Company.find(params[:id])
    end
    
    def create
    	@company = Company.new(company_params)
    	if @company.save
    		redirect_to @company
    	else
    		render 'new'
    	end
    end

    def update
    	@company = Company.new(company_params)

    	if @company.save
    		redirect_to @company 
    	else 
    		render 'new'
    	end
    end

    def destroy
    	@company = Company.find(params[:id])
    	@company.destroy

    	redirect_to companies_path
    end
    
    private
    def company_params
    	params.require(:company).permit(:company)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	def create
    @company = Company.find(params[:company_id])
    @location = @company.locations.create(location_params)
    redirect_to company_path(@company)
  end
 
  def destroy
    @company = Company.find(params[:company_id])
    @location = @company.locations.find(params[:id])
    @location.destroy
    redirect_to company_path(@company)
  end
 
  private
    def location_params
      params.require(:location).permit(:address, :address1, :city, :state, :zip, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f|%>
<% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@company.errors.count, "error") %> prohibited
        this company from being saved:
      </h2>
      <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <%= f.label :company %><br>
  <%= f.text_field :company %>
  </p>
  <p>
  <%= f.submit %>
  </p>
  <% end %>

app/views/companies/edit.html.erb
<h1> Edit Contact </h1>
<%= render 'form' %>
 <%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
  <form>
  <%= select_tag "company", options_from_collection_for_select(@companies,"id", "company"), id: "simple-example" %>
  </form>

  

app/views/companies/new.html.erb
<h1>New Company </h1>
<%= render 'form' %>
<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p>
	<strong>Company:</strong>
	<%=@company.company %>
	<%= link_to 'Edit', edit_company_path(@company) %>
	<%= link_to 'Destroy', company_path(@company),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <h2>Locations</h2>
    <%= render @company.locations %>
 
<h2>Add a location:</h2>
<%= render 'locations/form' %>
	<%= link_to 'Back', companies_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MidwestPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <%= yield %>
</body>

</html>

app/views/locations/_form.html.erb
<%= form_for([@company, @company.locations.build]) do |f| %>
  <p>
    <%= f.label :address %><br>
    <p><%= f.text_field :address %></p>
    <p><%= f.text_field :address1 %></p>
  </p>
  <p>
  	<%= f.text_field :city ,:size=>20 %>
  	<%= f.text_field :state ,:size=>2 %>
  	<%= f.text_field :zip ,:size=>5%>
  <p>
    <%= f.label :phone %><br>
    <%= f.telephone_field(:phone) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/locations/_location.html.erb
  <p>
    <strong>Address:</strong>
    <p><%= location.address%></p>

    <p><%= location.address1 %></p>
	<p><%= location.city%> <%=location.state %> <%=location.zip %></p>
  </p>
 
  <p>
    <strong>phone:</strong>
    <%= location.phone %>
  </p>
 <p>
  <%= link_to 'Destroy Location', [location.company, location],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>